### ISSUE TITLE
"Type Error" in Quiz

### ISSUE THREAD

**Issue by hiepluonghlv** [nusedutech/coursemology.org#21]
in CS2100: Quiz 1

---

Showing /home/eadm/public_html/coursemology.org/app/views/assessment/training_submissions/_edit_form.html.erb where line #70 raised:

can't convert nil into String

---

I believe this error only come up when we enable "Allow Discussion" in the setup.

Another bug occurs when you edit the training setup _after_ the questions have been added.

Steps to reproduce the bug:
1. Create a quiz, add some questions
2. Edit the quiz property, then "update training"
3. The quiz now contains 0 questions (i.e. all questions have been dropped)!

**Comment by Weiyuan-Lane** [comment]
Refering only for the second issue

fixed @ https://github.com/nusedutech/coursemology.org/commit/9a5363528f3bad4610fa2dc9c902a0097588f86a

**Comment by Weiyuan-Lane** [comment]
Referring only for the first issue

fixed @ https://github.com/nusedutech/coursemology.org/commit/3c5bc074c15d55365d5463642d72bbcd8f6a3606

**Comment by sooyj** [comment]
Thanks for the quick response. Are the fixes deployed?

**Comment by hiepluonghlv** [comment]
Not yet Dr Soo, Weiyuan and I will merge code to main branch and then update server.

**Comment by sooyj** [comment]
May I know the status of this fix? Thanks!

**Comment by hiepluonghlv** [comment]
The fixes are merged to main branch and will be deployed after customizing test (normal training) feature which could be done today.
