### ISSUE TITLE
Concept tags disappears in MCQ creation

### ISSUE THREAD

**Issue by sooyj** [nusedutech/coursemology.org#28]
Concept, difficulty tags no longer shows up in MCQ creation.

We also encounter the following bug when we key in the tags explicitly:

JSON::ParserError in Assessment::McqQuestionsController#create

A JSON text must at least contain two octets!
Rails.root: /home/eadm/public_html/coursemology.org
Application Trace | Framework Trace | Full Trace
app/controllers/assessment/mcq_questions_controller.rb:35:in `block in create'
app/controllers/assessment/mcq_questions_controller.rb:31:in`create'

**Comment by hiepluonghlv** [comment]
Fixed, wait for updating server
