### ISSUE TITLE
Urgent: Import IVLE students not working

### ISSUE THREAD

**Issue by sooyj** [nusedutech/coursemology.org#6]
I'm unable to import IVLE students. After clicking on the students => finish import, I receive the following error:

![image](https://cloud.githubusercontent.com/assets/8551571/5623834/8ab0c0b6-9595-11e4-8f50-38d672a7217a.png)

Also, the "Select All" checkbox to select all students is not working.

**Comment by sooyj** [comment]
As a follow up, I'm able to add a few students at a time. It is possible that we cannot click the "Finish Import" more than 1 time?

**Comment by hiepluonghlv** [comment]
checked
